#!/bin/sh
#: Title       : Digitsonly
#: Date        : 2016-04-07
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Is this a valid nonnegative integer?
#: Options     : N/A
##
## -- Main ---------------------------------------------------------------------
main() {
    case $1 in                ## If the string contains..
        *[!0-9]*) return 1 ;; ## Non-numerical characters, return error status;
    esac                      ## Else Return normally (0)
}
##
## -- Run! ---------------------------------------------------------------------
main ${1+"$1"} ## Call the main funciton w/one argument if any

