#!/bin/sh
#: Title       : Report
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#: Description : Prints formated sales report
#: Options     : N/A
##
## -- Main func. declaration  --------------------------------------------------
main() {
    # Local variables (If local is used, it should appear as the first
    # statement of a function)
    local divider header format totalwidth
    # Initialize locals
    divider===================================== # Long string of equals signs
    header="\n %-10s %11s %8s %10s\n"            # Format strings for printf
    format=" %-10s %11.2f %8d %10.2f\n"          # (*)
    totalwidth=44                                # With of divider
    # Extend divider
    divider=$divider$divider
    # Print categories (header)
    printf "$header" ITEM "PER UNIT" NUM TOTAL
    # Print divider to match width of report
    printf "%$totalwidth.${totalwidth}s\n" "$divider"
    # Print lines of report
    printf "$format" \
	   Chair 79,95 4 3198,8 \
	   Table 209,99 1 209,99 \
	   Armchair 315,49 2 630,98
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
##
## (*)Note : Olthough the "f" fromat specifier is supported by Dash's printf,
##           As per Posix specifications, it does NOT need to bue supported.
##           Further information following belo link:
##           http://pubs.opengroup.org/onlinepubs/9699919799/utilities/
##           printf.html
