#!/bin/sh
#: Title       : Showvar
#: Date        : 2016-04-12
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Print value of Variable x
#: Options     : N/A
##
## -- Main ---------------------------------------------------------------------
main() {
    if [ "${x+X}" != X ]; then ## Is global var x unset (null pointer)? (*)
        printf " %s is not set\n" "\$x"
        return 0
    fi
    if [ X"$x" = X ]; then     ## Is global var x empty (null string)?
	printf " \$x is set but empty\n"
        return 0
    fi
    printf " \$x = %s\n" "$x"
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
##
## (*)Note: As per posix shell parameter expansion ${x+X} Will be expanded to
##          "X" only when x is set
