#!/bin/sh
#: Title       : Randomize2
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Prints formated random numbers to file and to variable
#: Options     : N/A
##
## -- Externals required for execution -----------------------------------------
type awk >/dev/null || exit 1 ## Pattern scanning and processing language
type tee >/dev/null || exit 1 ## Reads from STDIN and pass to files and STDOUT
##
## -- Main ---------------------------------------------------------------------
main() {
    # Local variables (If local is used, it should appear as the first
    # statement of a function)
    local digits format outfile outvar
    # Initialize locals
    digits=5                              # Digits per random number to display
    format=" %${digits}d.%-5${digits}d\n" # Single line output format
    outfile=$HOME/randoms                 # File to print output
    outvar=                               # Variable to print output
    # Create awk's printf format string (1)
    format=$format$format$format$format
    # Use awk to generate random numbers (2)
    outvar=$(awk '
BEGIN{ srand();       ## Initialize seed for random numbers sequence
printf("'"$format"'", ## Pass format string to awks printf
       int(32767*rand()), int(32767*rand()), ## Generate 4 pairs of rand numbrs,
       int(32767*rand()), int(32767*rand()), ## each must be lower than 32767
       int(32767*rand()), int(32767*rand()),
       int(32767*rand()), int(32767*rand())) }' | tee $outfile)
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
##
## (1)Note: Awk's printf() does not re-use the format so we need to append
## (2)Note: $RANDOM is not available for Dash, nor it is required by POSIX
