#!/bin/sh
#: Title       : hw
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Prints "Hello, World!"
#: Options     : N/A
##
## -- Main func. declaration  --------------------------------------------------
main() { # The main function declaration
    # Function's body section
    printf "%s\n" "Hello, World!" ## Output the message
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
