#!/bin/sh
#: Title       : Fileutils
#: Date        : 2016-05-17
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Dash function declarations file
#:             : 
#: Options     : N/A


dname() {
    case $1 in
        */*) ## Does provided path contain any "/" char?
            printf "%s\n" "${1%/*}" ;;
        *)   ## Assume that provided path is relative pointing to a file in $PWD
             ## But if it doesn't exists, print a dot.
            [ -e "$1" ] && printf "%s\n" "$PWD" || printf ".\n" ;;
    esac
}

bname() {
    # Get dname from path and then strip it from the beginning of path (*)
    printf "%s\n" "${1##"$(dname "$1")"/}"
}