#!/bin/sh
#: Title       : Fleutls
#: Date        : 2016-05-17
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Dash function declarations file
#:             : Provides tools to work w/files
#: Options     : N/A
##
## -- Includes -----------------------------------------------------------------
. /usr/local/lib/nmeutls || exit 1 ## Utils for shell names
##
## Declarations
if [ "X$_SRC_FLEUTLS" = X ]; then ## Do not include if already included
    readonly _SRC_FLEUTLS=:       ## Already sourced (included) test flag
    
dname() { #@ DESCRIPTION:
          #@ USAGE: dnme NAME [ PATH ]
    case $2 in
        */*) ## Does provided path contain any "/" char?
            setvar $1 "${2%/*}" ;;
        *)   ## Assume provided path is relative pointing to file in $PWD, but
             ## if it doesn't exists, return dot.
            [ -e "$2" ] && setvar $1 "$PWD" || setvar $1 . ;;
    esac
}
bname() {
    case $2 in
        */*)
            setvar $1 "${2##*/}" ;;
        *)
            [ -e "$2" ]
    esac
}
fi
