#!/bin/sh
#: Title       : Stdioutils
#: Date        : 2016-05-17
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Dash function declarations file
#:             : Provides usefull IO tools
#: Options     : N/A
##
## Declarations
if [ "X$_SRC_NMEUTILS" = X ]; then ## Do not include if already included
    readonly _SRC_NMEUTILS=:       ## Already sourced (included) test flag    
stdmsg() { #@ DESCRIPTION: Print messages to STDOUT
           #@ USAGE: stdmsg [ MSG ... ]
    [ "${1+X}" = X ] && printf "%s\n" "$@"
}
errmsg() { #@ DESCRIPTION: Print messages to STDERR prefixed by an error stamp
           #@ USAGE: stderr [ MSG ... ]
    stdmsg ${1+"Error! $@"} >&2
}
fi
