#!/bin/sh
#: Title       : bp1
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : a. Creates a directory inside $HOME
#:             : b. Populates it with two subdirectories, bin and scripts
#: Options     : N/A
##
## -- Required for execution ---------------------------------------------------
type mkdir >/dev/null || exit 1 ## Require access to mkdir command or finish
##
## -- Main func. declaration  --------------------------------------------------
main() { # The main function declaration
    # Function's body section
    mkdir $HOME/bp1                       ## Create the directory inside $HOME
    mkdir $HOME/bp1/bin $HOME/bp1/scripts ## Populate it w/subdirs
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
