#!/bin/sh
#: Title       : Chw
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : a. Writes a script that creates the "Hello, World!" script file
#:             :    called "hw"
#:             : b. Creates it inside $HOME/bp1/bin
#:             : c. Makes it executable
#:             : d. And then executes it
#: Options     : N/A
##
## -- External commands required for execution ---------------------------------
type chmod >/dev/null || exit 1 ## Require access to chmod command or finish
##
## -- Main func. declaration  --------------------------------------------------
main() {
    # Local variables (If local is used, it should appear as the first
    # statement of a function)
    local script code ## (*)
    script=$HOME/bp1/bin/hw ## Initialize local script's path and code
    code="#!/bin/sh
#: Title       : hw
#: Date        : 2016-04-06
#: Author      : \"Kybernetes\" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Prints \"Hello, World!\"
#: Options     : N/A
##
## -- Main func. declaration  --------------------------------------------------
main() { # The main function declaration
    # Function's body section
    printf \"%s\\n\" \"Hello, World!\" ## Output the message
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
"
    # Write code to script
    printf "%s" "$code" >$script
    # Make script file executable
    chmod -v u+x $script
    # Execute it in current shell's environment
    . $script
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
##
## (*) Note: Olthough local is supported by Dash, and mos of of available shells
##           It is not defined by POSIX. For additional information follow below
##           link:
##           https://stackoverflow.com/questions/18597697/posix-compliant-way-
##           to-scope-variables-to-a-function-in-a-shell-script
