#!/bin/sh
#: Title       : Rangecheck
#: Date        : 2016-04-06
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script file
#:             : Prompt for a number and check that it is within a given range
#: Options     : N/A
##
## -- Main ---------------------------------------------------------------------
main() {
    # Local variables ("local" must be function's first statement)
    local number
    # Prompt user to enter a value for number
    printf "Eneter a number between 10 and 20 inclusive: "
    # Read entered number to number variable
    read number
    # Check entered value is within range
    if [ $number -lt 10 ]; then                       ## Is entered value <10?
	printf "Error! %d is too low\n" $number >&2   ## Yes so, finish w/errors
	return 1
    elif [ $number -gt 20 ]; then                     ## No, so is value >20?
	printf "Error! %d is too high\n" $number >&2  ## Yes so, finish w/errors
	return 1
    else                                              ## Now that value is        
	printf "You entered %d\n" $number             ## in range, display it
    fi
}
##
## -- Run! ---------------------------------------------------------------------
main ## Call the main funciton
